/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Movie } from './types';

export const GLOBAL_MOVIE_DATABASE: Omit<Movie, 'id' | 'addedAt' | 'watched'>[] = [
  {
    title: 'Inception',
    year: 2010,
    director: 'Christopher Nolan',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    rating: '8.8 IMDb',
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    vibe: 'Cerebral Puzzle',
    streamingServices: ['Netflix', 'Apple TV', 'Prime Video'],
    whySave: 'Saved from a list of the greatest cerebral sci-fi puzzle films of all time.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80',
    runtime: '148 mins',
    confidence: 99,
    language: 'English',
    favorite: true,
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy']
  },
  {
    title: 'Everything Everywhere All at Once',
    year: 2022,
    director: 'Daniel Kwan, Daniel Scheinert',
    synopsis: 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
    rating: '8.5 IMDb',
    genres: ['Sci-Fi', 'Adventure', 'Comedy', 'Action'],
    vibe: 'Multiverse Chaos',
    streamingServices: ['Prime Video', 'Apple TV'],
    whySave: 'Highly requested mind-bending cinematic feat that dominated the Academy Awards.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    runtime: '139 mins',
    confidence: 97,
    language: 'English',
    favorite: false,
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu', 'Jamie Lee Curtis']
  },
  {
    title: 'Pulp Fiction',
    year: 1994,
    director: 'Quentin Tarantino',
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    rating: '8.9 IMDb',
    genres: ['Crime', 'Drama'],
    vibe: 'Retro Cool',
    streamingServices: ['Netflix', 'Prime Video'],
    whySave: 'Classic post-modern indie film that redefined cinematic editing and dialogue.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80',
    runtime: '154 mins',
    confidence: 98,
    language: 'English',
    favorite: false,
    cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman', 'Bruce Willis']
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    synopsis: 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    rating: '8.4 IMDb',
    genres: ['Animation', 'Action', 'Adventure', 'Sci-Fi'],
    vibe: 'Pure Adrenaline',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'A revolutionary step in cinematic animation, color grading, and superhero storytelling.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=600&q=80',
    runtime: '117 mins',
    confidence: 96,
    language: 'English',
    favorite: true,
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali']
  },
  {
    title: 'The Dark Knight',
    year: 2008,
    director: 'Christopher Nolan',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    rating: '9.0 IMDb',
    genres: ['Action', 'Crime', 'Drama'],
    vibe: 'Gothic Thriller',
    streamingServices: ['Max', 'Apple TV', 'Prime Video'],
    whySave: 'Arguably the greatest comic book adaptation ever made, driven by Heath Ledger\'s iconic performance.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    runtime: '152 mins',
    confidence: 99,
    language: 'English',
    favorite: true,
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal']
  },
  {
    title: 'The Matrix',
    year: 1999,
    director: 'Lana Wachowski, Lilly Wachowski',
    synopsis: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    rating: '8.7 IMDb',
    genres: ['Sci-Fi', 'Action'],
    vibe: 'Cerebral Puzzle',
    streamingServices: ['Max', 'Netflix', 'Apple TV'],
    whySave: 'A genre-defining masterpiece that blends high-concept philosophical questions with legendary action sequence choreography.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    runtime: '136 mins',
    confidence: 98,
    language: 'English',
    favorite: false,
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving']
  },
  {
    title: 'Blade Runner 2049',
    year: 2017,
    director: 'Denis Villeneuve',
    synopsis: 'A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\'s left of society into chaos.',
    rating: '8.0 IMDb',
    genres: ['Sci-Fi', 'Mystery', 'Drama'],
    vibe: 'Cosmic Wonder',
    streamingServices: ['Apple TV', 'Prime Video', 'Netflix'],
    whySave: 'Visually dazzling, slow-burn cyberpunk noir with breathtaking Roger Deakins cinematography.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    runtime: '164 mins',
    confidence: 95,
    language: 'English',
    favorite: false,
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks']
  },
  {
    title: 'Coherence',
    year: 2013,
    director: 'James Ward Byrkit',
    synopsis: 'Strange things begin to happen when a group of friends gather for a dinner party on an evening when a comet is passing overhead.',
    rating: '7.2 IMDb',
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    vibe: 'Cerebral Puzzle',
    streamingServices: ['Prime Video', 'Apple TV'],
    whySave: 'A low-budget psychological sci-fi thriller that relies purely on tension and brain-melting logic.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
    runtime: '89 mins',
    confidence: 94,
    language: 'English',
    favorite: true,
    cast: ['Emily Baldoni', 'Maury Sterling', 'Nicholas Brendon', 'Lorene Scafaria']
  },
  {
    title: 'Arrival',
    year: 2016,
    director: 'Denis Villeneuve',
    synopsis: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft land around the world.',
    rating: '7.9 IMDb',
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    vibe: 'Cosmic Wonder',
    streamingServices: ['Netflix', 'Prime Video', 'Apple TV'],
    whySave: 'A brilliant, emotional, and deeply smart exploration of language, memory, and cosmic communication.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    runtime: '116 mins',
    confidence: 96,
    language: 'English',
    favorite: false,
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker', 'Michael Stuhlbarg']
  },
  {
    title: 'The Grand Budapest Hotel',
    year: 2014,
    director: 'Wes Anderson',
    synopsis: 'A writer relates his adventures at a renowned European resort hotel between the first and second World Wars with a concierge who is wrongly framed for murder.',
    rating: '8.1 IMDb',
    genres: ['Comedy', 'Drama', 'Adventure'],
    vibe: 'Cozy Nostalgia',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'A delightfully eccentric, beautifully symmetrical, and deeply warm pastel comedy about friendship and memories.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1542204172-e7052809a1a1?auto=format&fit=crop&w=600&q=80',
    runtime: '100 mins',
    confidence: 95,
    language: 'English',
    favorite: true,
    cast: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric', 'Saoirse Ronan']
  },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    year: 2004,
    director: 'Michel Gondry',
    synopsis: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
    rating: '8.3 IMDb',
    genres: ['Drama', 'Romance', 'Sci-Fi'],
    vibe: 'Cerebral Puzzle',
    streamingServices: ['Prime Video', 'Apple TV'],
    whySave: 'A mind-bending romantic masterpiece about why we need the beauty of painful memories.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&w=600&q=80',
    runtime: '108 mins',
    confidence: 97,
    language: 'English',
    favorite: true,
    cast: ['Jim Carrey', 'Kate Winslet', 'Kirsten Dunst', 'Mark Ruffalo', 'Elijah Wood']
  },
  {
    title: 'Perfect Days',
    year: 2023,
    director: 'Wim Wenders',
    synopsis: 'Hirayama seems utterly content with his simple life as a cleaner of toilets in Tokyo. Outside of his very structured everyday routine he enjoys his passion for music and books.',
    rating: '7.9 IMDb',
    genres: ['Drama'],
    vibe: 'Cozy Nostalgia',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'A quiet, peaceful, and visually splendid slice-of-life that serves as a warm hug for the soul.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    runtime: '124 mins',
    confidence: 95,
    language: 'Japanese',
    favorite: false,
    cast: ['Koji Yakusho', 'Arisa Nakano', 'Tokio Emoto', 'Aoi Yamada']
  },
  {
    title: 'Amélie',
    year: 2001,
    director: 'Jean-Pierre Jeunet',
    synopsis: 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.',
    rating: '8.3 IMDb',
    genres: ['Comedy', 'Romance'],
    vibe: 'Cozy Nostalgia',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'A whimsical, highly stylish romance that is universally guaranteed to brighten your evening.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=600&q=80',
    runtime: '122 mins',
    confidence: 96,
    language: 'French',
    favorite: false,
    cast: ['Audrey Tautou', 'Mathieu Kassovitz', 'Rufus', 'Lorella Cravotta']
  },
  {
    title: 'Predestination',
    year: 2014,
    director: 'Michael Spierig, Peter Spierig',
    synopsis: 'For his final assignment, a top temporal agent must pursue the one criminal that has eluded him throughout time.',
    rating: '7.4 IMDb',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    vibe: 'Cerebral Puzzle',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'One of the most complex, paradox-heavy, mind-melting time travel movies ever conceived.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1454789548928-9efd52dc4031?auto=format&fit=crop&w=600&q=80',
    runtime: '97 mins',
    confidence: 93,
    language: 'English',
    favorite: false,
    cast: ['Ethan Hawke', 'Sarah Snook', 'Noah Taylor', 'Madeleine West']
  },
  {
    title: 'Roma',
    year: 2018,
    director: 'Alfonso Cuarón',
    synopsis: 'A year in the life of a middle-class family\'s housekeeper in Mexico City in the early 1970s.',
    rating: '7.7 IMDb',
    genres: ['Drama'],
    vibe: 'Artistic Slow-Burn',
    streamingServices: ['Netflix'],
    whySave: 'A monochromatic cinematic masterwork composed of long takes and stunning atmospheric soundscapes.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=600&q=80',
    runtime: '135 mins',
    confidence: 94,
    language: 'Spanish',
    favorite: false,
    cast: ['Yalitza Aparicio', 'Marina de Tavira', 'Diego Cortina Autrey']
  },
  {
    title: 'Drive',
    year: 2011,
    director: 'Nicolas Winding Refn',
    synopsis: 'A mysterious Hollywood action method stuntman and stunt driver double moonlights as a getaway driver and finds himself in trouble when he helps his neighbor.',
    rating: '7.8 IMDb',
    genres: ['Action', 'Drama', 'Crime'],
    vibe: 'Retro Cool',
    streamingServices: ['Apple TV', 'Prime Video'],
    whySave: 'A moody neo-noir thriller powered by an iconic synth-pop soundtrack and gorgeous neon lights.',
    socialSource: { platform: 'manual', author: 'CineSave Curator' },
    posterUrl: 'https://images.unsplash.com/photo-1543536448-d209d2d13a1c?auto=format&fit=crop&w=600&q=80',
    runtime: '100 mins',
    confidence: 95,
    language: 'English',
    favorite: false,
    cast: ['Ryan Gosling', 'Carey Mulligan', 'Bryan Cranston', 'Albert Brooks']
  }
];
